const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="grandrp_pov_entries_v3";
const state={entries:JSON.parse(localStorage.getItem(KEY)||"[]"),files:[],filter:"all",editing:null,selectedTypes:[],accessToken:sessionStorage.getItem("yt_access_token")||"",tokenClient:null,clientId:localStorage.getItem("yt_client_id")||""};
const views={archive:["Archiv","POV-Fälle, Bans und PC-Checks"],cases:["Verdachtsfälle","Nicht eindeutig erkannte Fälle zur manuellen Prüfung"],upload:["POVs hochladen","Mehrere Aufnahmen gleichzeitig verarbeiten"],settings:["Einstellungen","YouTube und OCR"]};
function save(){localStorage.setItem(KEY,JSON.stringify(state.entries))}function esc(s){return String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function showView(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=views[v][0];$('#pageSubtitle').textContent=views[v][1];if(v==='archive')renderArchive();if(v==='cases')renderCases()}
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#newUploadBtn').onclick=()=>showView('upload');$('#emptyUploadBtn').onclick=()=>showView('upload');$('#reloadBtn').onclick=()=>renderArchive();$('#casesRefresh').onclick=()=>renderCases();
$('#search').oninput=renderArchive;
$$('.filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderArchive()});

const dz=$('#dropzone'), input=$('#fileInput');$('#chooseBtn').onclick=e=>{e.stopPropagation();input.click()};dz.onclick=e=>{if(e.target.closest('button'))return;input.click()};input.onchange=e=>addFiles([...e.target.files]);
['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles([...e.dataTransfer.files].filter(f=>f.type.startsWith('video/'))));
function addFiles(files){if(!files.length)return;const newOnes=files.map(file=>({id:crypto.randomUUID(),file,status:'Wartet auf Verarbeitung',progress:0,result:null,processing:false}));state.files.push(...newOnes);renderQueue();processQueue()}
function renderQueue(){const q=$('#uploadQueue');$('#queueCount').textContent=`${state.files.length} ${state.files.length===1?'Datei':'Dateien'}`;q.innerHTML=state.files.map(f=>`<div class="queue-item" id="q-${f.id}"><div class="queue-icon">▶</div><div class="queue-name"><strong>${esc(f.file.name)}</strong><small>${formatSize(f.file.size)} · ${f.status}</small><div class="progress"><i style="width:${f.progress}%"></i></div></div><div class="queue-status">${esc(f.result?.id?`ID ${f.result.id}`:'')}</div><div class="queue-actions"><button class="mini-btn edit-q" data-id="${f.id}">Bearbeiten</button><button class="mini-btn remove-q" data-id="${f.id}">×</button></div></div>`).join('');$$('.edit-q').forEach(b=>b.onclick=()=>openEditor(state.files.find(x=>x.id===b.dataset.id)));$$('.remove-q').forEach(b=>b.onclick=()=>{state.files=state.files.filter(x=>x.id!==b.dataset.id);renderQueue()})}
function formatSize(n){return n>1024**3?(n/1024**3).toFixed(1)+' GB':n>1024**2?(n/1024**2).toFixed(1)+' MB':(n/1024).toFixed(0)+' KB'}
async function processQueue(){for(const item of state.files){if(item.processing||item.status==='Analyse fertig'||item.status==='YouTube hochgeladen')continue;item.processing=true;renderQueue();try{item.status='Datei wird vollständig eingelesen';item.progress=5;renderQueue();const video=$('#videoProbe');video.src=URL.createObjectURL(item.file);await loaded(video);item.progress=15;item.status='Upload abgeschlossen · OCR startet';renderQueue();item.result=await analyzeVideo(video,video.duration,(p,msg)=>{item.progress=Math.max(15,Math.min(92,p));item.status=msg;renderQueue()});item.status=item.result.found?'Analyse fertig · bitte prüfen':'Manuelle Eingabe erforderlich';item.progress=100;renderQueue();openEditor(item)}catch(e){console.error(e);item.status='Fehler: '+e.message;item.progress=0;renderQueue()}finally{item.processing=false}}}
function loaded(v){return new Promise((res,rej)=>{v.onloadedmetadata=()=>res();v.onerror=()=>rej(new Error('Video konnte nicht gelesen werden.'))})}
function seek(v,t){return new Promise((res,rej)=>{const done=()=>{v.removeEventListener('seeked',done);res()};v.addEventListener('seeked',done);v.currentTime=Math.min(Math.max(0,t),Math.max(0,v.duration-.05));setTimeout(()=>{v.removeEventListener('seeked',done);rej(new Error('Video-Suche timeout'))},10000)})}
function crop(v,x,y,w,h){const c=$('#ocrCanvas'),vw=v.videoWidth,vh=v.videoHeight;c.width=Math.max(1,Math.round(vw*w));c.height=Math.max(1,Math.round(vh*h));c.getContext('2d').drawImage(v,Math.round(vw*x),Math.round(vh*y),c.width,c.height,0,0,c.width,c.height);return c}
async function ocr(c,w){return (await w.recognize(c)).data.text||''}
async function analyzeVideo(video,duration,onProgress){const frames=Math.max(4,Math.min(20,Number(localStorage.getItem('frame_count')||10))),start=Math.max(0,duration-40),span=Math.max(.1,duration-start);const worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')onProgress(20+(m.progress||0)*70,'OCR läuft · '+Math.round((m.progress||0)*100)+'%')}});const left=[],right=[],dates=[];try{for(let i=0;i<frames;i++){await seek(video,start+span*((i+.5)/frames));left.push(await ocr(crop(video,0,0,.62,.38),worker));right.push(await ocr(crop(video,.62,0,.38,.30),worker));dates.push(await ocr(crop(video,.68,.70,.32,.30),worker));onProgress(20+(i+1)/frames*70,`OCR · Frame ${i+1}/${frames}`)}}finally{await worker.terminate()}const all=[...left,...right,...dates].join('\n');return parseBanData(left.join('\n'),right.join('\n'),dates.join('\n'),all)}
function clean(s){return s.replace(/\s+/g,' ').trim()}
function parseBanData(left,right,dateText,all){const src=(left+'\n'+all).replace(/\|/g,'I');let id='';let m=src.match(/hat\s+(.{2,100}?)\s*\[(\d{1,8})\]\s*(?:f[uü]r|fur|für)/i);if(!m)m=src.match(/(?:Name|Player|Spieler)[^\[]{0,60}\[(\d{1,8})\]/i);if(m)id=m[2]||m[1];const scM=src.match(/\bSC\s*[:\-]?\s*([A-Za-z0-9][A-Za-z0-9_-]{9,})/i);const sc=scM?scM[1]:'';let reason='';let r=src.match(/(?:grund)\s*[:\-]?\s*([^\n]{2,100})/i);if(r)reason=clean(r[1].replace(/\bSC\s*[:\-]?.*$/i,''));if(!reason){r=src.match(/(?:gebannt|banned|ban)\s+(?:wegen|grund)?\s*[:\-]?\s*([A-Za-z][A-Za-z0-9 _-]{2,60})/i);if(r)reason=clean(r[1])}const serverM=right.match(/(?:server|srv)\s*[:#\-]?\s*(\d{1,2})/i)||right.match(/\b([1-9]|10)\b/);const server=serverM?serverM[1]:'';return{id,reason,sc,server,date:extractDate(dateText)||today(),found:!!(id&&sc)}}
function extractDate(s){let m=s.match(/\b(20\d{2})[.\-/](\d{1,2})[.\-/](\d{1,2})\b/);if(m)return`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;m=s.match(/\b(\d{1,2})[.\-/](\d{1,2})[.\-/](20\d{2})\b/);return m?`${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`:''}

function openEditor(item){state.editing=item;state.selectedTypes=item.types||[];$('#modalTitle').textContent='POV bearbeiten';$('#modalFile').textContent=item.file.name;const p=item.result||{};$('#targetId').value=p.id||'';$('#reason').value=p.reason||'';$('#sc').value=p.sc||'';$('#server').value=p.server||'';$('#date').value=p.date||today();$('#perma').checked=!!item.perma;$('#notBanned').checked=!!item.notBanned;$$('#banTypes .chip').forEach(c=>c.classList.toggle('active',state.selectedTypes.includes(c.dataset.value)));$('#ocrWarning').classList.toggle('hidden',!!p.found);updateTitle();$('#editorModal').classList.remove('hidden')}
function closeEditor(){$('#editorModal').classList.add('hidden');state.editing=null}$('#closeModal').onclick=closeEditor;$('#cancelBtn').onclick=closeEditor;
$$('#banTypes .chip').forEach(c=>c.onclick=()=>{c.classList.toggle('active');state.selectedTypes=$$('#banTypes .chip.active').map(x=>x.dataset.value);updateTitle()});
['#targetId','#reason','#date'].forEach(s=>$(s).oninput=updateTitle);function updateTitle(){const id=$('#targetId').value.trim()||'UNBEKANNT',r=$('#reason').value.trim()||'Unbekannt',d=$('#date').value||today();$('#titlePreview').value=`${id}, ${r}, ${d}`}
$('#perma').onchange=e=>{if(e.target.checked)$('#notBanned').checked=false};$('#notBanned').onchange=e=>{if(e.target.checked)$('#perma').checked=false};
$('#entryForm').onsubmit=async e=>{e.preventDefault();const item=state.editing;if(!item)return;const entry={id:$('#targetId').value.trim(),reason:$('#reason').value.trim(),sc:$('#sc').value.trim(),server:$('#server').value.trim(),date:$('#date').value||today(),types:[...state.selectedTypes],perma:$('#perma').checked,notBanned:$('#notBanned').checked,filename:`${$('#targetId').value.trim()||'UNBEKANNT'}, ${$('#reason').value.trim()||'Unbekannt'}, ${$('#date').value||today()}${ext(item.file.name)}`,fileName:item.file.name,createdAt:new Date().toISOString(),youtubeId:'',status:'Gespeichert',videoUrl:URL.createObjectURL(item.file)};if(!entry.id&&!entry.notBanned){toast('ID fehlt. Bitte ergänzen.');return}$('#saveBtn').disabled=true;$('#saveBtn').textContent='Wird verarbeitet …';try{if(state.accessToken&&!entry.notBanned){entry.youtubeId=await uploadToYouTube(item.file,entry);entry.status='YouTube · Nicht gelistet'}else if(!state.accessToken)entry.status='Gespeichert · YouTube nicht verbunden';else entry.status='Gespeichert · nicht gebannt';state.entries.unshift(entry);save();state.files=state.files.filter(x=>x.id!==item.id);closeEditor();renderQueue();renderArchive();toast(entry.youtubeId?'POV hochgeladen und archiviert.':'Eintrag gespeichert.');showView('archive')}catch(err){toast('Upload fehlgeschlagen: '+err.message)}finally{$('#saveBtn').disabled=false;$('#saveBtn').textContent='Speichern & YouTube hochladen'}};
function ext(n){const m=n.match(/\.[^.]+$/);return m?m[0]:'.mp4'}
async function uploadToYouTube(file,entry){const metadata={snippet:{title:`${entry.id}, ${entry.reason||entry.types.join(' + ')||'POV'}, ${entry.date}`,description:`Server: ${entry.server||'unbekannt'}\nSC: ${entry.sc||'unbekannt'}\nPerma-Bann: ${entry.perma?'Ja':'Nein'}\nBann-Typen: ${entry.types.join(', ')}`},status:{privacyStatus:'unlisted',selfDeclaredMadeForKids:false}};const init=await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:'Bearer '+state.accessToken,'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Length':String(file.size),'X-Upload-Content-Type':file.type||'application/octet-stream'},body:JSON.stringify(metadata)});if(!init.ok)throw new Error(await init.text());const url=init.headers.get('Location');if(!url)throw new Error('Keine YouTube-Upload-URL erhalten.');let start=0,chunk=8*1024*1024;while(start<file.size){const end=Math.min(start+chunk,file.size)-1,res=await fetch(url,{method:'PUT',headers:{'Content-Length':String(end-start+1),'Content-Range':`bytes ${start}-${end}/${file.size}`},body:file.slice(start,end+1)});if(res.status===308){const range=res.headers.get('Range');start=range?parseInt(range.split('-')[1])+1:end+1}else if(res.ok)return(await res.json()).id;else throw new Error(await res.text())}}

function renderArchive(){const q=$('#search').value.toLowerCase();const e=state.entries.filter(x=>{const types=x.types||[];let ok=state.filter==='all'||(state.filter==='hardban'&&types.some(t=>['hardban','socban','cheater','negativ'].includes(t)))||(state.filter==='hardbanOnly'&&types.includes('hardban'))||(state.filter==='socban'&&types.includes('socban'))||(state.filter==='cheater'&&types.includes('cheater'))||(state.filter==='negativ'&&types.includes('negativ'))||(state.filter==='pccheck'&&types.includes('pccheck'))||(state.filter==='novideo'&&!x.youtubeId);return ok&&JSON.stringify(x).toLowerCase().includes(q)});$('#countAll').textContent=state.entries.length;$('#countBan').textContent=state.entries.filter(x=>(x.types||[]).some(t=>['hardban','socban','cheater','negativ'].includes(t))).length;$('#countPc').textContent=state.entries.filter(x=>(x.types||[]).includes('pccheck')).length;$('#countSoc').textContent=state.entries.filter(x=>(x.types||[]).includes('socban')).length;$('#countHard').textContent=state.entries.filter(x=>(x.types||[]).includes('hardban')).length;$('#countCheat').textContent=state.entries.filter(x=>(x.types||[]).includes('cheater')).length;$('#countNeg').textContent=state.entries.filter(x=>(x.types||[]).includes('negativ')).length;$('#countNoVideo').textContent=state.entries.filter(x=>!x.youtubeId).length;$('#archiveGrid').innerHTML=e.map((x)=>`<article class="entry"><div class="thumb">${x.videoUrl?`<video src="${esc(x.videoUrl)}" muted></video>`:'<div class="thumb-placeholder">◉</div>'}<div class="badge-row">${(x.types||[]).map(t=>`<span class="type-badge">${esc(t)}</span>`).join('')}<span class="server-badge">Server ${esc(x.server||'?')}</span></div></div><div class="entry-body"><h3>${esc(x.id||'Nicht gebannt')} · ${esc(x.reason||'Kein Grund')}</h3><div class="meta"><div>ID<strong>${esc(x.id||'—')}</strong></div><div>Datum<strong>${esc(x.date)}</strong></div><div>SC<strong>${esc(x.sc||'—')}</strong></div><div>Perma<strong>${x.perma?'Ja':'Nein'}</strong></div></div><div class="entry-foot"><span>${esc(x.status)}</span><div class="entry-actions"><button class="mini-btn edit-entry" data-id="${esc(x.createdAt)}">Bearbeiten</button><button class="mini-btn del-entry" data-id="${esc(x.createdAt)}">Löschen</button></div></div></div></article>`).join('');$('#emptyState').classList.toggle('hidden',e.length>0);$$('.del-entry').forEach(b=>b.onclick=()=>{state.entries=state.entries.filter(x=>x.createdAt!==b.dataset.id);save();renderArchive()});$$('.edit-entry').forEach(b=>b.onclick=()=>{const x=state.entries.find(x=>x.createdAt===b.dataset.id);if(x){state.files=[{id:x.createdAt,file:new File([],x.fileName||x.filename),result:x,perma:x.perma,notBanned:x.notBanned}];openEditor(state.files[0])}})}
function renderCases(){const bad=state.files.filter(x=>x.result&&!x.result.found);$('#casesList').innerHTML=bad.length?bad.map(x=>`<div class="case-row"><div><strong>${esc(x.file.name)}</strong><small>OCR konnte die Bannzeile nicht eindeutig erkennen.</small></div><button class="mini-btn edit-q" data-id="${x.id}">Daten ergänzen</button></div>`).join(''):'<div class="empty"><h2>Keine offenen Verdachtsfälle</h2><p>Alle bisher erkannten Fälle sind geprüft.</p></div>';$$('.edit-q').forEach(b=>b.onclick=()=>openEditor(state.files.find(x=>x.id===b.dataset.id)))}

function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3500)}
$('#clientId').value=state.clientId;$('#clientId').oninput=e=>{state.clientId=e.target.value.trim();localStorage.setItem('yt_client_id',state.clientId);initGoogle()};$('#frameCount').value=localStorage.getItem('frame_count')||10;$('#frameCount').onchange=e=>localStorage.setItem('frame_count',e.target.value);
function initGoogle(){if(!window.google?.accounts?.oauth2||!state.clientId)return;state.tokenClient=google.accounts.oauth2.initTokenClient({client_id:state.clientId,scope:'https://www.googleapis.com/auth/youtube.upload',callback:r=>{if(r.error)return toast('Google-Anmeldung abgebrochen.');state.accessToken=r.access_token;sessionStorage.setItem('yt_access_token',state.accessToken);updateYtStatus()}})}
$('#connectYoutube').onclick=()=>{initGoogle();if(!state.tokenClient)return toast('Bitte zuerst die Google OAuth Client-ID eintragen.');state.tokenClient.requestAccessToken({prompt:'consent'})};$('#disconnectYoutube').onclick=()=>{state.accessToken='';sessionStorage.removeItem('yt_access_token');updateYtStatus()};function updateYtStatus(){$('#ytStatus').innerHTML=state.accessToken?'<span class="status-dot"></span>YouTube verbunden':'<span class="status-dot muted-dot"></span>Nicht verbunden'}setTimeout(initGoogle,1000);
window.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}if(e.key==='Escape')closeEditor()});
renderArchive();showView('archive');
